version: '3.9'

services:

  postgres-db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    volumes:
      - 'postgres-db-data:/var/lib/psql'
    ports:
      - '127.0.0.1:5432:5432'


  pgadmin:
    image: dpage/pgadmin4:8.3
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: 12345
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - 'pgadmin-data:/var/lib/pgadmin'
    ports:
      - '127.0.0.1:15432:80'
    depends_on:
      - postgres-db

volumes:
  postgres-db-data:
  pgadmin-data: